### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This still does not solve the Py3 problems that I have with this, but it helps.

**Comment by s0undt3ch** [comment]
TCP/IPC unit tests pass in Py2, but not in Py3. Closer though...

**Comment by s0undt3ch** [comment]
I'm touching parts of Salt's crypt, let's just see if the overall tests pass with that change, if not, we revert those changes.

**Comment by s0undt3ch** [comment]
Actually, let's not use this just yet. Carry on your work, I'll get back to py3 compat when I have more time(at which time your PR will, most likely, be merged already)

**Comment by jacksontj** [comment]
Do we have CI for py3 compat?

**Comment by s0undt3ch** [comment]
We do some py3 linting but obviously it does not catch everything.

There's been some work done on py3 compatibility but it hasn't reached the crypt layer.

**Pull request closed without merging**
